### ISSUE TITLE
invalid CEN header (bad signature)

### ISSUE THREAD

**Issue by slacrey** [zeroturnaround/zt-zip#114]
Hello.

I am using this library to unzip a file in a desktop application but I have an error with this stacktrace. The problem occurs sometimes and I don't found any cause or solution.

org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: invalid CEN header (bad signature)

	at org.zeroturnaround.zip.ZipExceptionUtil.rethrow(ZipExceptionUtil.java:11)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:522)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:977)
	at com.eqxiu.video.render.utils.ExtractUtilsTest.unpackZip(ExtractUtilsTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:279)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:499)
	... 24 more
This is the call to unzip the file ZipUtil.unpack(file, outputDir)

This is the version of the library in my pom.xml file.

<dependency>
	<groupId>org.zeroturnaround</groupId>
	<artifactId>zt-zip</artifactId>
	<version>1.13</version>
</dependency>

ant like this：
        Project project = new Project();
        Expand expand = new Expand();
        expand.setProject(project);
        expand.setSrc(new File(sourceZip));
        expand.setOverwrite(false);
        expand.setDest(new File(destDir));
        expand.setEncoding(encoding);
        expand.execute();

is ok？？？？

**Comment by toomasr** [comment]
Do you have the offending zip file for me to test?

**Comment by david-espinosa** [comment]
Hi @slacrey , I'm reproducing the same error using allure 2.13.0. Did you manage to solve it?

**Comment by toomasr** [comment]
@david-espinosa do you happen to have an offending file to test the issue?

**Comment by david-espinosa** [comment]
Hey @toomasr  I don't get your point, this errors raises when I try to create the allure-report from a junit xml file.

**Comment by toomasr** [comment]
From the initial post I see that the error appears on expanding/unzipping an archive. I'm trying to find an archive that produces this exception. Or am I missing something?
