### ISSUE TITLE
Folder packing: File not found

### ISSUE THREAD

**Issue by DATL4G** [zeroturnaround/zt-zip#127]
I'm trying to pack a directory to a zip archive.
```java
public static File folderToFile(@NotNull Context context, @NotNull File file) {
        File tempDir = context.getCacheDir();
        File tempFile = null;
        try {
            tempFile = File.createTempFile(file.getName()+"_TEMP", ".zip", tempDir);
        } catch (IOException e) {
            e.printStackTrace();
        }
        ZipUtil.pack(file, file);
        Objects.requireNonNull(tempFile).deleteOnExit();

        return tempFile;
    }
```
`file` is the directory and I'm creating a temporary file `tempFile` wich should be the output

When I choose a folder this lib throws an error
```
Caused by: java.io.FileNotFoundException: /storage/emulated/0/matlog/saved_logs (Is a directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
        at org.zeroturnaround.zip.ZipUtil.pack(ZipUtil.java:1626)
```

I have tried choosing the matlog folder and the saved_logs folder
Same result for both
And inside the saved_logs folder are 2 .txt files

What am I doing wrong?

**Comment by DATL4G** [comment]
My fault!
I packed wrong file (duplicate)
