### ISSUE TITLE
Serious Bug : Error in Opening Zip File

### ISSUE THREAD

**Issue by goxr3plus** [zeroturnaround/zt-zip#128]
I am having the following zip file which is a valid not corrupted zip file and can be opened with zip explorer on windows or 7zip .

[Deposit1571307514.zip](https://github.com/zeroturnaround/zt-zip/files/3739645/Deposit1571307514.zip)

But when i try your library to unpack it i am getting the following error :
I will remove it from our dependencies because it had cause an issue in production .
What can be the cause :) ?

``` Java
org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: error in opening zip file
	at org.zeroturnaround.zip.ZipExceptionUtil.rethrow(ZipExceptionUtil.java:11)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:522)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:996)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:939)
```

**Comment by goxr3plus** [comment]
@toomasr Tomas please let me know  :)

**Comment by goxr3plus** [comment]
Probably , i tried also with `zip4j` and it reported **missing zip headers** .

I think the .zip is either corrupted or not created correctly , just wanted to report .

I go it from a client using our endpoint with the .zip he created .
