### ISSUE TITLE
 Terrible Error!!!!!!!!!!!!!!!!! Failed to process zip entry && FileNotFoundException

### ISSUE THREAD

**Issue by Pluckypan** [zeroturnaround/zt-zip#99]
`org.zeroturnaround.zip.ZipException: Failed to process zip entry '1711202017/res/face1/face1_00010.png' with action org.zeroturnaround.zip.ZipUtil$Unpacker@3460cc
at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:428)
at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:831)
at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:814)
at com.xxx.framework.utils.io.ZipFileUtils.unZip(ZipFileUtils.java:25)
at com.xxx.videotool.app.ar.activity.ArManager.unzipAndRecord(ArManager.java:151)
at com.xxx.videotool.app.ar.activity.ArManager.init(ArManager.java:81)
at com.xxx.videotool.app.ar.activity.ArManager.initAtApplication(ArManager.java:72)
at com.xxx.videotool.application.VideoToolApplication$1.run(VideoToolApplication.java:83)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.xxx/material/ar/offline/1711202017/res/face1/face1_00010.png (No such file or directory)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:287)
at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
at org.zeroturnaround.zip.commons.FileUtils.copy(FileUtils.java:54)
at org.zeroturnaround.zip.ZipUtil$Unpacker.process(ZipUtil.java:964)
at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:425)
at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:831)
at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:814)
at com.xxx.framework.utils.io.ZipFileUtils.unZip(ZipFileUtils.java:25)
at com.xxx.videotool.app.ar.activity.ArManager.unzipAndRecord(ArManager.java:151)
at com.xxx.videotool.app.ar.activity.ArManager.init(ArManager.java:81)
at com.xxx.videotool.app.ar.activity.ArManager.initAtApplication(ArManager.java:72)
at com.xxx.videotool.application.VideoToolApplication$1.run(VideoToolApplication.java:83)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)`

**Comment by Pluckypan** [comment]
nexus6p android 8.0.0 huawei

**Comment by reinra** [comment]
Can you check whether the same works with normal Java (not Android)?

**Comment by Pluckypan** [comment]
em,it works normally with normal java. but error happened when works with Android on nexus6p.but it's not 100% happened.

**Comment by toomasr** [comment]
Is it the same zip archive every time? Any chance pinpointing down what is different during the times when it isn't working vs time when it is working?

**Comment by Pluckypan** [comment]
well,in fact,i have no idea yet.but i am sure it's the same zip.

**Comment by Pluckypan** [comment]
good news.i found that there is an app named [ES File Explorer](https://play.google.com/store/apps/details?id=com.estrongs.android.pop),when i uninstall it,the error not happened again.

**Comment by reinra** [comment]
Thanks for the info.
Maybe it was related to one of its features:
`Real-time Observer：help load recently added files in library 80% faster`
So if you could just disable this feature you could still use that app as well.
